// utils/foodComponentDatabase.js
export const foodComponents = {
  // --- Surse de Proteine ---
  chicken_breast: {
    name: "Chicken Breast",
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    unit: "g",
  },
  chicken_thigh: {
    name: "Chicken Thigh",
    calories: 209,
    protein: 26,
    carbs: 0,
    fats: 10.9,
    unit: "g",
  },
  salmon: {
    name: "Salmon Fillet",
    calories: 208,
    protein: 20,
    carbs: 0,
    fats: 13,
    unit: "g",
  },
  cod: {
    name: "Cod Fillet",
    calories: 82,
    protein: 18,
    carbs: 0,
    fats: 0.7,
    unit: "g",
  },
  tuna_canned: {
    name: "Canned Tuna in water",
    calories: 116,
    protein: 26,
    carbs: 0,
    fats: 0.8,
    unit: "g",
  },
  steak: {
    name: "Beef Steak (Sirloin)",
    calories: 205,
    protein: 29,
    carbs: 0,
    fats: 9,
    unit: "g",
  },
  pork_loin: {
    name: "Pork Loin",
    calories: 143,
    protein: 26,
    carbs: 0,
    fats: 3.5,
    unit: "g",
  },
  eggs: {
    name: "Eggs",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fats: 11,
    unit: "g",
  },
  greek_yogurt: {
    name: "Greek Yogurt 2%",
    calories: 73,
    protein: 10,
    carbs: 3.9,
    fats: 2,
    unit: "g",
  },
  cottage_cheese: {
    name: "Cottage Cheese 2%",
    calories: 81,
    protein: 12,
    carbs: 4.8,
    fats: 2.3,
    unit: "g",
  },
  tofu: {
    name: "Tofu",
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fats: 4.8,
    unit: "g",
  },
  lentils_cooked: {
    name: "Cooked Lentils",
    calories: 116,
    protein: 9,
    carbs: 20,
    fats: 0.4,
    unit: "g",
  },
  chickpeas_cooked: {
    name: "Cooked Chickpeas",
    calories: 139,
    protein: 7.6,
    carbs: 27,
    fats: 2.1,
    unit: "g",
  },
  protein_powder: {
    name: "Whey Protein",
    calories: 375,
    protein: 80,
    carbs: 5,
    fats: 3,
    unit: "g",
  },

  // --- Surse de Carbohidrați ---
  oats: {
    name: "Oats",
    calories: 389,
    protein: 16.9,
    carbs: 66,
    fats: 6.9,
    unit: "g",
  },
  white_rice_cooked: {
    name: "Cooked White Rice",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
    unit: "g",
  },
  brown_rice_cooked: {
    name: "Cooked Brown Rice",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fats: 0.9,
    unit: "g",
  },
  quinoa_cooked: {
    name: "Cooked Quinoa",
    calories: 120,
    protein: 4.4,
    carbs: 21,
    fats: 1.9,
    unit: "g",
  },
  pasta_cooked: {
    name: "Cooked Pasta",
    calories: 131,
    protein: 5,
    carbs: 25,
    fats: 1.1,
    unit: "g",
  },
  potatoes: {
    name: "Potatoes",
    calories: 77,
    protein: 2,
    carbs: 17,
    fats: 0.1,
    unit: "g",
  },
  sweet_potatoes: {
    name: "Sweet Potatoes",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fats: 0.1,
    unit: "g",
  },
  bread: {
    name: "Whole Wheat Bread",
    calories: 247,
    protein: 13,
    carbs: 41,
    fats: 3.4,
    unit: "g",
  },
  banana: {
    name: "Banana",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fats: 0.3,
    unit: "g",
  },
  berries_mixed: {
    name: "Mixed Berries",
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fats: 0.3,
    unit: "g",
  },

  // --- Surse de Grăsimi ---
  avocado: {
    name: "Avocado",
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fats: 15,
    unit: "g",
  },
  olive_oil: {
    name: "Olive Oil",
    calories: 884,
    protein: 0,
    carbs: 0,
    fats: 100,
    unit: "g",
  },
  almonds: {
    name: "Almonds",
    calories: 579,
    protein: 21,
    carbs: 22,
    fats: 49,
    unit: "g",
  },
  walnuts: {
    name: "Walnuts",
    calories: 654,
    protein: 15,
    carbs: 14,
    fats: 65,
    unit: "g",
  },
  peanut_butter: {
    name: "Peanut Butter",
    calories: 588,
    protein: 25,
    carbs: 20,
    fats: 50,
    unit: "g",
  },
  chia_seeds: {
    name: "Chia Seeds",
    calories: 486,
    protein: 17,
    carbs: 42,
    fats: 31,
    unit: "g",
  },

  // --- Legume ---
  broccoli: {
    name: "Broccoli",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fats: 0.4,
    unit: "g",
  },
  spinach: {
    name: "Spinach",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fats: 0.4,
    unit: "g",
  },
  bell_pepper: {
    name: "Bell Pepper",
    calories: 20,
    protein: 0.9,
    carbs: 4.6,
    fats: 0.2,
    unit: "g",
  },
  mixed_salad_greens: {
    name: "Mixed Salad Greens",
    calories: 15,
    protein: 1.5,
    carbs: 2.9,
    fats: 0.2,
    unit: "g",
  },
};
