// utils/mealDatabase.js

export const mealDatabase = [
  // --- Mic Dejun (Breakfast) ---
  {
    id: 1,
    name: "Scrambled Eggs (3) with Spinach",
    type: "breakfast",
    calories: 350,
    protein: 25,
    carbs: 5,
    fats: 25,
    tags: ["keto", "low-carb", "vegetarian"],
  },
  {
    id: 2,
    name: "Oatmeal with Berries & Nuts",
    type: "breakfast",
    calories: 400,
    protein: 15,
    carbs: 55,
    fats: 15,
    tags: ["vegan", "vegetarian"],
  },
  {
    id: 3,
    name: "Greek Yogurt (200g) with Honey",
    type: "breakfast",
    calories: 300,
    protein: 20,
    carbs: 30,
    fats: 10,
    tags: ["vegetarian"],
  },
  {
    id: 10,
    name: "Avocado Toast with Egg",
    type: "breakfast",
    calories: 380,
    protein: 18,
    carbs: 30,
    fats: 20,
    tags: ["vegetarian"],
  },

  // --- Prânz (Lunch) ---
  {
    id: 4,
    name: "Grilled Chicken (150g) Salad",
    type: "lunch",
    calories: 500,
    protein: 45,
    carbs: 10,
    fats: 30,
    tags: ["low-carb"],
  },
  {
    id: 5,
    name: "Quinoa Bowl with Black Beans & Avocado",
    type: "lunch",
    calories: 550,
    protein: 20,
    carbs: 70,
    fats: 22,
    tags: ["vegan", "vegetarian"],
  },
  {
    id: 6,
    name: "Salmon (150g) with Asparagus",
    type: "lunch",
    calories: 450,
    protein: 40,
    carbs: 10,
    fats: 28,
    tags: ["keto", "low-carb"],
  },
  {
    id: 11,
    name: "Beef Chili",
    type: "lunch",
    calories: 520,
    protein: 40,
    carbs: 45,
    fats: 20,
    tags: [],
  },

  // --- Cină (Dinner) ---
  {
    id: 7,
    name: "Steak (200g) with Broccoli",
    type: "dinner",
    calories: 600,
    protein: 50,
    carbs: 15,
    fats: 40,
    tags: ["keto", "low-carb"],
  },
  {
    id: 8,
    name: "Lentil Soup",
    type: "dinner",
    calories: 400,
    protein: 20,
    carbs: 60,
    fats: 10,
    tags: ["vegan", "vegetarian"],
  },
  {
    id: 9,
    name: "Tofu Stir-fry with Vegetables",
    type: "dinner",
    calories: 450,
    protein: 25,
    carbs: 40,
    fats: 20,
    tags: ["vegan", "vegetarian"],
  },
  {
    id: 12,
    name: "Cod Fillet with Roasted Vegetables",
    type: "dinner",
    calories: 480,
    protein: 45,
    carbs: 30,
    fats: 20,
    tags: ["low-carb"],
  },

  // --- Gustări (Snacks) - CHEIA SUCCESULUI ---
  {
    id: 100,
    name: "Protein Shake",
    type: "snack",
    calories: 200,
    protein: 30,
    carbs: 5,
    fats: 5,
    tags: ["vegetarian"],
  },
  {
    id: 101,
    name: "Apple with Peanut Butter",
    type: "snack",
    calories: 250,
    protein: 8,
    carbs: 30,
    fats: 12,
    tags: ["vegan", "vegetarian"],
  },
  {
    id: 102,
    name: "Handful of Almonds (30g)",
    type: "snack",
    calories: 180,
    protein: 6,
    carbs: 6,
    fats: 15,
    tags: ["vegan", "vegetarian", "keto"],
  },
  {
    id: 103,
    name: "Rice Cakes (2) with Hummus",
    type: "snack",
    calories: 150,
    protein: 5,
    carbs: 25,
    fats: 3,
    tags: ["vegan", "vegetarian"],
  },
  {
    id: 104,
    name: "Hard-boiled Egg (1)",
    type: "snack",
    calories: 80,
    protein: 6,
    carbs: 1,
    fats: 5,
    tags: ["vegetarian", "keto"],
  },
  {
    id: 105,
    name: "Small Banana",
    type: "snack",
    calories: 90,
    protein: 1,
    carbs: 23,
    fats: 0,
    tags: ["vegan", "vegetarian"],
  },
];
